baseURL                         = "https://aaltomcc.github.io/cs-ej4101-fall-2019-101-advanced/"
languageCode                    = "en-us"
title                           = "My New Hugo Site"
theme                           = "introduction"
DefaultContentLanguage          = "en"

[params]
    themeStyle                  = "light"
    fadeIn                      = "true"
    dateFormat                  = "Jan 2, 2006"
    email                       = "tin.lun@aalto.fi"

    [params.home]
        introHeight             = "fullheight"
        showLatest              = true
        showAllPOsts            = false
        localTime               = true
        timeZone                = "Europe/Helsinki"
        timeFormat              = "hh:mm"
    
