baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-101-advanced/"
languageCode = "en-us"
title = "Sanna"
theme = "mediumish-gohugo-theme"
summaryLength = 25
enableEmoji = true
publishDir = "docs"

[params]
  description ="Welcome to my blog"

[params.author]
  name = "Sanna"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/author.png"
  title = "Sanna"
  subtitle = ""
  mdtext = '''


'''
  alertbar = false

[params.social]
  github = "moisanna"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
