baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-101-advanced/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Sanna Lun"
title = "cs-ej4101-fall-2019-101-advanced"
theme = "hugo-goa"

## Site settings
[params]
author = "Sanna Lun"
intro = "Hongkonger living in Finland"
authorimage = "046b530537225123bd842e3e6980d0ad.jpg"
description = "Description"
dateformat = "Jan 2, 2006"

## Main Menu
[[menu.main]]
    name = "posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"


## Social accounts 
[params.social]
github = "moisanna"
email = "tin.lun@aalto.fi"
goodreads = "sannalun"

## Extras
[params.extra]
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false